"""Golden original-file checks and in-memory corruptions; no test writes."""

from contextlib import redirect_stderr, redirect_stdout
import io
import json
from pathlib import Path
import struct
import subprocess
import sys
import unittest

sys.dont_write_bytecode = True
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))
import inspect_itxd as itxd

SAMPLE = ROOT / "build/extracted/frontend_global.itxd"
SOURCE = ROOT / "Simpsons Game, The (USA)/frontend/frontend_global.str"

# Independently recorded from original resource words, not generated by the parser.
# name, dimension, format id, pitch texels, max mip, payload offset, payload size
GOLDEN = [
    ("square", 16, 18, 128, 0, 0x1000, 0x2000),
    ("hud_target_center", 32, 19, 128, 0, 0x3000, 0x4000),
    ("target_railshooter", 32, 19, 128, 0, 0x7000, 0x4000),
    ("targeting_nontarget", 32, 19, 128, 0, 0xb000, 0x4000),
    ("hittarget", 64, 19, 128, 0, 0xf000, 0x4000),
    ("healthbar", 64, 19, 128, 0, 0x13000, 0x4000),
    ("fakeshdw", 64, 2, 64, 0, 0x17000, 0x1000),
    ("targeting_f2f", 64, 19, 128, 0, 0x18000, 0x4000),
    ("hud_targetlock", 64, 19, 128, 0, 0x1c000, 0x4000),
    ("targeting_firearm", 64, 19, 128, 2, 0x20000, 0xc000),
    ("hud_targetlock02", 128, 19, 128, 0, 0x2c000, 0x4000),
    ("projtex_hog", 256, 18, 256, 4, 0x30000, 0x10000),
    ("projtex_sax", 256, 18, 256, 4, 0x40000, 0x10000),
    ("texture_not_specified", 256, 18, 256, 4, 0x50000, 0x10000),
    ("texture_not_found", 256, 18, 256, 4, 0x60000, 0x10000),
]


class ITXDTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.data = SAMPLE.read_bytes()
        if itxd.sha256(cls.data) != itxd.SAMPLE_SHA256:
            raise AssertionError("tests require the exact original extracted sample")
        cls.report = itxd.parse_itxd(cls.data)

    def changed(self, *words):
        data = bytearray(self.data)
        for offset, value in words:
            struct.pack_into(">I", data, offset, value)
        return data

    def reject(self, data, message):
        with self.assertRaisesRegex(itxd.ITXDError, message):
            itxd.parse_itxd(data)

    def test_original_provenance(self):
        p = itxd.verify_original(self.data, SOURCE)
        self.assertTrue(p["verified_byte_identical"])
        self.assertEqual(p["source_sha256"], "ae967348ebe5a0ed022c13cc372a3e53831a86f26804c76159ac1c8203b6388a")
        self.assertEqual((p["source_size"], p["entry_file_offset"], p["entry_stored_size"],
                          p["entry_decoded_size"], p["refpack_consumed_bytes"],
                          p["payload_decoded_offset"], p["payload_size"]),
                         (79872, 4096, 75776, 469488, 75716, 256, 458752))

    def test_original_mismatch_rejected(self):
        altered = bytearray(self.data)
        altered[-1] ^= 1
        with self.assertRaisesRegex(itxd.ITXDError, "not byte-identical"):
            itxd.verify_original(altered, SOURCE)

    def test_all_fifteen_golden_records(self):
        actual = []
        for item in self.report["textures"]:
            d, p = item["descriptor"], item["payload"]
            self.assertEqual(d["width"], d["height"])
            self.assertEqual(item["record_offset"], 0x30 + len(actual) * 0x100)
            actual.append((item["name"], d["width"], d["format"]["id"], d["base_pitch_texels"],
                           d["mip_max_level"], p["offset"], p["size"]))
        self.assertEqual(actual, GOLDEN)

    def test_exact_partition_and_hashes(self):
        self.assertEqual(self.report["dictionary"]["inspected_metadata_end"], 0xf30)
        self.assertEqual(self.report["dictionary"]["padding_bytes"], 208)
        self.assertEqual(self.report["summary"]["payload_bytes"], 454656)
        chunks = [self.data[x[5]:x[5] + x[6]] for x in GOLDEN]
        self.assertEqual(b"".join(chunks), self.data[4096:])
        for record, payload in zip(self.report["textures"], chunks):
            self.assertEqual(record["payload"]["sha256"], itxd.sha256(payload))

    def test_descriptor_channel_swizzle_and_compression_geometry(self):
        items = self.report["textures"]
        self.assertEqual(items[0]["descriptor"]["channel_swizzle"], list("XYZW"))
        self.assertEqual(items[6]["descriptor"]["channel_swizzle"], list("XXX1"))
        self.assertEqual(items[6]["descriptor"]["endianness"], "none")
        self.assertEqual(items[0]["descriptor"]["endianness"], "8in16")
        self.assertEqual([items[i]["payload"]["logical_base_level_bytes"] for i in (0, 1, 6, 11)],
                         [128, 1024, 4096, 32768])
        self.assertEqual(self.report["summary"]["format_counts"],
                         {"k_DXT1": 5, "k_DXT2_3": 9, "k_8": 1})

    def test_mip_and_sampler_evidence_is_not_an_authored_count(self):
        items = self.report["textures"]
        self.assertEqual(self.report["summary"]["packed_mip_count"], 5)
        self.assertEqual([items[i]["descriptor"]["mip_address_field_bytes"] for i in (0, 9, 11)],
                         [0, 0x4000, 0x8000])
        self.assertEqual(items[0]["sampler_candidate"]["raw"], "0x00003302")
        self.assertEqual(items[9]["sampler_candidate"]["raw"], "0x00001106")
        self.assertEqual(items[9]["descriptor"]["stored_sampler"]["mip_filter"], "point")
        self.assertTrue(any("not proof of authored mip count" in x for x in self.report["limitations"]))

    def test_header_rejections(self):
        for offset, value, message in ((0, 0, "header signature"), (0x18, 0x31, "first texture"),
                                       (0x1c, 0xfffffff0, "last record"),
                                       (0x28, 0, "first texture"), (0x20, 1, "header control")):
            with self.subTest(offset=offset):
                self.reject(self.changed((offset, value)), message)

    def test_truncation_and_trailing_bytes(self):
        for length in (0, 47, 0x100, 0xf30, len(self.data) - 1):
            with self.subTest(length=length):
                self.reject(self.data[:length], "length|bounds")
        self.reject(self.data + b"\0", "trailing bytes")

    def test_list_cycle(self):
        self.reject(self.changed((0x30, 0x30), (0x128, 0xa0)), "cycle")

    def test_list_backlink(self):
        self.reject(self.changed((0x134, 0x18)), "backlink")

    def test_premature_list_end(self):
        self.reject(self.changed((0x30, 0x18), (0x128, 0)), "dictionary tail")

    def test_noncontiguous_list(self):
        self.reject(self.changed((0x30, 0x230), (0x128, 0x2a0)), "non-contiguous")

    def test_nested_resource_links(self):
        for rel in (0x70, 0xa4, 0xf8):
            with self.subTest(rel=rel):
                self.reject(self.changed((0x30 + rel, 0)), "pointer mismatch|next nested reference")

    def test_names(self):
        for name, raw in (("empty", bytes(64)), ("unterminated", b"A" * 64),
                          ("nonascii", b"\xff\0" + bytes(62)),
                          ("padding", b"A\0B" + bytes(61))):
            with self.subTest(name=name):
                data = bytearray(self.data)
                data[0x38:0x78] = raw
                self.reject(data, "name")
        data = bytearray(self.data)
        data[0x138:0x178] = data[0x38:0x78]
        self.reject(data, "duplicate")

    def test_dimension_cross_checks(self):
        for rel in (0x7c, 0x80, 0x98, 0x9c):
            with self.subTest(rel=rel):
                self.reject(self.changed((0x30 + rel, 8)), "dimensions disagree")

    def test_invalid_descriptor_type_dimension_and_tiling(self):
        for rel, value, message in ((0xe0, 0x81000003, "not a texture"),
                                    (0xf4, 0x600, "non-stacked 2D"),
                                    (0xe4, 0x452, "non-stacked 2D"),
                                    (0xe8, 0x0401e00f, "non-stacked 2D"),
                                    (0xe0, 0x01000002, "linear texture")):
            with self.subTest(rel=rel, value=value):
                self.reject(self.changed((0x30 + rel, value)), message)

    def test_invalid_format_pitch_swizzle_and_controls(self):
        for rel, value, message in ((0xe4, 63, "unsupported texture format"),
                                    (0xe0, 0x80000002, "base pitch"),
                                    (0xec, 0x0d1e, "swizzle selector"),
                                    (0xe4, 0x1052, "base-address"),
                                    (0xec, 0x080d10, "sampler/control"),
                                    (0x58, 1, "profile word")):
            with self.subTest(rel=rel, value=value):
                self.reject(self.changed((0x30 + rel, value)), message)

    def test_invalid_mip_limits_addresses_and_correlations(self):
        base = 0x930
        for rel, value, message in ((0xf0, 0x8c, "mip min/max"),
                                    (0xf0, 0x1c0, "mip min/max"),
                                    (0xf4, 0x4200, "packed-mip/address"),
                                    (0xf4, 0xca00, "mip address field exceeds"),
                                    (0xac, 0x01000101, "mip byte"),
                                    (0x90, 0x04000003, "mip flag"),
                                    (0x48, 0x1102, "sampler/mip")):
            with self.subTest(rel=rel, value=value):
                self.reject(self.changed((base + rel, value)), message)

    def test_unsupported_raster_format_depth_and_sampler(self):
        for rel, value, message in ((0x84, 32, "raster depth"),
                                    (0xbc, 0x1a200153, "format word"),
                                    (0x48, 0x1107, "engine sampler"),
                                    (0x90, 0x040000ff, "raster flags")):
            with self.subTest(rel=rel):
                self.reject(self.changed((0x30 + rel, value)), message)

    def test_payload_extent_rejections(self):
        for rel, value in ((0xb8, 0xfffff000), (0xb8, 0x1001),
                           (0xb8, 0), (0xb4, 0), (0xb4, 0xffffffff)):
            with self.subTest(rel=rel, value=value):
                self.reject(self.changed((0x30 + rel, value)), "payload extent")

    def test_payload_partition_and_logical_size_rejections(self):
        for offset in (0x3000, 0x8000):
            with self.subTest(offset=offset):
                self.reject(self.changed((0x230 + 0xb8, offset)), "overlap, gap")
        self.reject(self.changed((0xe30 + 0xb4, 0x1000)), "logical base-level")
        data = bytearray(self.data)
        data[0xf30] = 1
        self.reject(data, "metadata alignment padding")

    def test_unknown_words_are_preserved_without_invented_validation(self):
        report = itxd.parse_itxd(self.changed((0x30 + 0x50, 0x12345678)))
        self.assertEqual(report["textures"][0]["opaque_words"]["0x00000050"], "0x12345678")
        self.assertFalse(report["input"]["matches_verified_sample"])

    def test_payload_corruption_is_not_falsely_claimed_detectable(self):
        data = bytearray(self.data)
        data[0x1000] ^= 1
        report = itxd.parse_itxd(data)
        self.assertFalse(report["input"]["matches_verified_sample"])
        self.assertNotEqual(report["textures"][0]["payload"]["sha256"],
                            self.report["textures"][0]["payload"]["sha256"])

    def test_deterministic_cli_stdout(self):
        outputs = []
        for _ in range(2):
            out = io.StringIO()
            with redirect_stdout(out):
                result = itxd.main(["--input", str(SAMPLE), "--source-str", str(SOURCE)])
            self.assertEqual(result, 0)
            outputs.append(out.getvalue())
        self.assertEqual(outputs[0], outputs[1])
        self.assertEqual(itxd.json_text(self.report), itxd.json_text(itxd.parse_itxd(self.data)))

    def test_cli_rejects_input_overwrite_without_writing(self):
        error = io.StringIO()
        with redirect_stderr(error):
            result = itxd.main(["--input", str(SAMPLE), "--output", str(SAMPLE)])
        self.assertEqual(result, 2)
        self.assertIn("aliases an input", error.getvalue())
        self.assertEqual(SAMPLE.read_bytes(), self.data)

    def test_subprocess_stdout_uses_canonical_utf8_lf_bytes(self):
        result = subprocess.run([sys.executable, "-B", str(ROOT / "tools/inspect_itxd.py"),
                                 "--input", str(SAMPLE)], check=True, capture_output=True, timeout=60)
        self.assertEqual(result.stderr, b"")
        self.assertEqual(result.stdout, itxd.json_text(json.loads(result.stdout)).encode("utf-8"))

    def test_output_source_tree_guard_without_writing(self):
        for root in (SOURCE.parent, Path("K:/Simpsons"), Path("K:/DarkRecomp")):
            with self.subTest(root=root):
                with self.assertRaisesRegex(itxd.ITXDError, "read-only source tree"):
                    itxd.write_report(root / "must_not_be_created.json", "{}", [SAMPLE])


if __name__ == "__main__":
    unittest.main()
