"""Generate native FX/material identity constants from the checked offline catalog.

The analyzer's --check is a mandatory authority gate, including original-image
identity, all envelope hashes, structure checks, and its mutation self-tests.
Only build/generated/effect_catalog.h is written; no original assets are exported.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess
import sys

sys.dont_write_bytecode = True
ROOT = Path(__file__).resolve().parents[1]
CATALOGS = (ROOT / "analysis/native-effect-catalog.json",
            ROOT / "analysis/native-post-effect-catalog.json")
OUTPUT = ROOT / "build/generated/effect_catalog.h"


def require(ok, message):
    if not ok:
        raise ValueError(message)


def sha_text(value):
    require(isinstance(value, str) and re.fullmatch(r"[0-9a-f]{64}", value), "Invalid SHA256 identity")
    return json.dumps(value)


def cpp_string(value):
    require(isinstance(value, str) and value and all(32 <= ord(c) < 127 for c in value), "Invalid catalog name")
    return json.dumps(value, ensure_ascii=True)


def number(value):
    require(type(value) is int and 0 <= value <= 0xFFFFFFFF, "Invalid u32 identity field")
    return f"0x{value:08X}u"


def render(raw_catalogs):
    catalogs = [json.loads(raw) for raw in raw_catalogs]
    require(len(catalogs) == 2, "Expected both original registration catalogs")
    rows = []
    for catalog, row_count, shader_count in zip(catalogs, (25, 24), (131, 84)):
        require(catalog["schema"] == 1, "Unsupported catalog schema")
        require(len(catalog["rows"]) == row_count, "Unexpected FX table row count")
        require(catalog["summary"]["unique_shaders"] == shader_count, "Unexpected per-table shader inventory")
        for i, row in enumerate(catalog["rows"]):
            require(row["index"] == i and not row["unrecognized_framing"], "Unqualified or reordered FX row")
            rows.append(row)
    require(catalogs[0]["source"] == catalogs[1]["source"], "Catalog original-image identities differ")
    require(catalogs[1]["shared_pool"]["common_eleven_or_exact_four_prefix"], "Unqualified second-table shared namespace")
    effects, materials, addresses, shader_keys = [], [], set(), set()
    stages = {"vertex": "MaterialStage::Vertex", "pixel": "MaterialStage::Pixel"}
    stage_counts = {"vertex": 0, "pixel": 0}
    for i, row in enumerate(rows):
        require(row["state_profile"] == "literal_only", "Unqualified FX state profile")
        va = int(row["blob_va"], 16)
        require(va not in addresses, "Duplicate FX address")
        addresses.add(va)
        effects.append("    {"+", ".join((number(va), number(row["bytes"]), number(i), cpp_string(row["name"]), sha_text(row["sha256"])))+"},")
        for shader in row["shaders"]:
            stage = shader["stage"]
            require(stage in stages, "Unknown shader stage")
            sva = int(shader["va"], 16)
            require(sva not in addresses, "Duplicate FX shader address")
            addresses.add(sva)
            key = (stage, shader["bytes"], shader["sha256"])
            require(key not in shader_keys, "Unexpected duplicate shader identity in admitted corpus")
            shader_keys.add(key)
            stage_counts[stage] += 1
            materials.append("    {"+", ".join((number(sva), stages[stage], number(shader["bytes"]), cpp_string(row["name"]), sha_text(shader["sha256"])))+"},")
    require(len(materials) == 215, "Expected 215 FX shader records")
    require(stage_counts == {"vertex": 110, "pixel": 105}, "Unexpected FX stage inventory")
    require(rows[0]["name"] == "fourtapblend" and rows[1]["name"] == "littextured", "Changed registration order")
    require(rows[25]["name"] == "simpsons_skin" and rows[48]["name"] == "simpsons_chocolate", "Changed second registration order")
    lines = [
        "// Generated by tools/generate_effect_catalog.py. Do not hand-edit.",
        *["// Source catalog SHA256: "+hashlib.sha256(raw).hexdigest() for raw in raw_catalogs],
        "// Original image SHA256: "+catalogs[0]["source"]["sha256"],
        "// Identities authorize immutable metadata ownership, not compilation or rendering.",
        "#pragma once", '#include "renderer/effect_resources.h"',
        "#include <array>", "", "namespace Simpsons::Graphics::Generated {", "",
        "// row is the combined ordinal: first table0..24, second table25..48.",
        "inline constexpr std::array<EffectIdentity,49> effectIdentities{{",
        *effects, "}};", "",
        "// Registration order, vertex array then pixel array; sentinels excluded.",
        "// Includes the two existing FourTap records exactly once at indices0/1.",
        "inline constexpr std::array<MaterialIdentity,215> effectMaterialIdentities{{",
        *materials, "}};", "", "}", "",
    ]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="check both authority and generated header, without writing")
    args = ap.parse_args()
    subprocess.run([sys.executable, "-B", str(ROOT/"tools/analyze_effect_catalog.py"), "--check"], cwd=ROOT, check=True, timeout=60)
    subprocess.run([sys.executable, "-B", str(ROOT/"tools/analyze_post_effect_catalog.py"), "--check"], cwd=ROOT, check=True, timeout=60)
    result = render([path.read_bytes() for path in CATALOGS])
    if args.check:
        require(OUTPUT.read_text(encoding="utf-8") == result, "Generated effect_catalog.h is stale")
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        # Avoid a needless rebuild when CMake invokes the generator again.
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != result:
            OUTPUT.write_text(result, encoding="utf-8", newline="\n")
    print("PASS: checked both original catalogs; 49 FX identities / 215 FX shader identities; "+str(OUTPUT))


if __name__ == "__main__":
    try:
        main()
    except (ValueError, KeyError, OSError, subprocess.CalledProcessError) as exc:
        print(str(exc), file=sys.stderr)
        sys.exit(1)
