"""Qualify exact original mono/stereo sounds in simpsons_chars_global.sbk."""
import importlib.util
import json
import os
from pathlib import Path
import sys
sys.dont_write_bytecode=True
import qualify_loc_resident_xma as loc
import qualify_resident_xma as q
from extract_resource import select_payload

ROOT=q.ROOT
OUT=ROOT/'build/characters-resident-xma'
BANK_HASH='4cedafc16ca0c681a0e4284ca8ae65e38ef19197ce29387a3ac8cac2ed50f078'

def main():
    root=ROOT/'Simpsons Game, The (USA)'
    data,provenance=select_payload(root/'simpsons_chars/simpsons_chars_global.str',4,'simpsons_chars_global.sbk',root)
    q.need(len(data)==1212431 and q.sha(data)==BANK_HASH,'Original characters bank changed')
    OUT.mkdir(parents=True,exist_ok=True);(OUT/'simpsons_chars_global.sbk').write_bytes(data)
    q.OUT=loc.OUT=OUT
    profiles=loc.discover(data,audio_offset=0x43C0,expected_count=69,expected_loops=3)
    spec=importlib.util.spec_from_file_location('characters_toolchain',ROOT/'tests/test_host_fp.py')
    tc=importlib.util.module_from_spec(spec);spec.loader.exec_module(tc)
    compiler,env=tc.toolchain();env['PATH']=str(q.INSTALL/'bin')+os.pathsep+env['PATH']
    q.run([sys.executable,'-B',ROOT/'tools/build_native_audio_codec.py','--verify'],env,'codec-verify')
    for rate in sorted({b['codec_rate'] for p in profiles for b in p['blocks']}):
        harness=q.CPP.replace('{channels,48000,',f'{{channels,{rate},').replace('frames<=262144','frames<=524288')
        source=OUT/f'harness-{rate}.cpp';source.write_text(harness, encoding="utf-8")
        q.run([compiler,'/nologo','/std:c++20','/EHsc','/MD','/O2','/fp:strict','/DNOMINMAX','/DWIN32_LEAN_AND_MEAN',
            f'/I{ROOT}',f'/I{q.INSTALL/"include"}',source,ROOT/'audio/native_xma_codec.cpp','/Fo'+str(OUT)+'\\',
            '/Fe'+str(OUT/f'harness-{rate}.exe'),'/link',q.INSTALL/'lib/avcodec-simpsonsxma.lib',
            q.INSTALL/'lib/avutil-simpsonsxma.lib','/INCREMENTAL:NO'],env,f'compile-{rate}',90)
    admitted=[];excluded={}
    for profile in profiles:
        try:
            for block in profile['blocks']:loc.qualify(data,block,env)
            admitted.append(profile);print('Qualified',profile['offset'],'loop',profile['loop_start'],flush=True)
        except RuntimeError as error:
            excluded[profile['offset']]=str(error);print('UNSUPPORTED',profile['offset'],str(error).splitlines()[0],flush=True)
    q.need(any(p['offset']==1061146 for p in admitted),'Reached characters sound did not qualify')
    q.need(q.sha((OUT/'simpsons_chars_global.sbk').read_bytes())==BANK_HASH,'Extracted characters bank changed')
    report=dict(bank_sha256=BANK_HASH,provenance=provenance,raw_eof_sent=False,profiles=admitted,excluded=excluded)
    (OUT/'report.json').write_text(json.dumps(report,indent=2)+'\n', encoding="utf-8")
    normal=[p['blocks'][0] for p in admitted if p['loop_start'] is None]
    loops=[p for p in admitted if p['loop_start'] is not None]
    lines=['// Generated by tools/qualify_characters_resident_xma.py after complete source verification.',
        '// Original simpsons_chars_global.sbk SHA256 '+BANK_HASH,'#pragma once','#include "resident_xma.h"',
        'namespace Simpsons::Audio {',f'inline constexpr std::array<ResidentXmaProfile,{len(normal)}> charactersResidentXmaProfiles = {{{{']
    lines+=['    '+loc.row(p)+',' for p in normal]+['}};']
    for p in loops:
        lines+=[f'inline constexpr std::array<ResidentXmaProfile,{len(p["blocks"])}> charactersLoop{p["offset"]} = {{{{']
        lines+=['    '+loc.row(b)+',' for b in p['blocks']]+['}};']
    lines+=[f'inline constexpr std::array<ResidentLoopProfile,{len(loops)}> charactersResidentLoopProfiles = {{{{']
    lines+=['    {'+f'{p["offset"]},{p["total_frames"]},{p["loop_start"]},charactersLoop{p["offset"]}'+'},' for p in loops]
    lines+=['}};','}'];(ROOT/'audio/characters_resident_xma_certificates.h').write_text('\n'.join(lines)+'\n', encoding="utf-8")
    print('PASS',len(normal),'normal sources,',len(loops),'loops;',len(excluded),'excluded',flush=True)
if __name__=='__main__':main()
