"""Qualify exact original Homer banks; unknown/failed records remain excluded."""
import argparse
import copy
import json
import os
from pathlib import Path
import shutil
import struct
import sys
sys.dont_write_bytecode = True
import qualify_loc_resident_xma as loc
import qualify_resident_xma as q
from extract_resource import select_payload

ROOT = q.ROOT
OUT = ROOT/'build/homer-resident-xma'
BANKS = (
    dict(name='homer.sbk', stem='homer', entry=3, size=2030922, metadata=0xB6B0,
         audio=0xB700, count=235, reached=1626873, symbol='homer',
         sha='a667c0b91b2f8a92c2254c334c5ab9fa13f9fb111f83d0370c12921c2bee9688'),
    dict(name='homer_fh0_gh0_hh0_h0.sbk', stem='homer_fh0_gh0_hh0_h0', entry=2,
         size=1776651, metadata=0x9A90, audio=0x9AC0, count=201, reached=1072283,
         symbol='homerVariant', sha='f14720a2436677a4f5d09a6008bb5bee346ecbdfc6567086687bb8c41e7d7a76'))
REACHED_HASH = '6967bc62eb8049b017206d814ffaf48fda67cff1bbed5a5260ff22ae3f450a69'


def extract(bank):
    root = ROOT/'Simpsons Game, The (USA)'
    data, provenance = select_payload(root/f'simpsons_chars/globalfolder/chars/{bank["stem"]}.str',
                                      bank['entry'], bank['name'], root)
    q.need(len(data) == bank['size'] and q.sha(data) == bank['sha'], 'Original Homer bank changed')
    q.need(struct.unpack_from('>IIII', data, 8) ==
           (bank['metadata'], bank['size']-bank['audio'], bank['audio'], bank['size']-bank['audio']),
           'Original Homer metadata/audio split changed')
    return data, provenance


def reuse_reached(profile):
    folder = ROOT/'build/homer-block-qualification'
    receipt = json.loads((folder/'receipt.json').read_text(encoding="utf-8"))
    q.need(receipt['block_sha256'] == REACHED_HASH and receipt['declared_frames'] == 51200
           and receipt['skip'] == 384 and receipt['restored_ff'] == 0, 'Reached receipt identity changed')
    q.need(q.sha((folder/'original.packets').read_bytes()) == receipt['packets_sha256'], 'Reached packets changed')
    raw = None
    for run in receipt['runs']:
        stem = f'{run["mode"]}-{run["split"]}'
        pcm = (folder/(stem+'.f32le')).read_bytes()
        log = (folder/(stem+'.log')).read_text(encoding="utf-8")
        q.need(q.sha(pcm) == run['raw_hash'] and len(pcm) == run['raw_frames']*4
               and 'no_eof_sent' in log and run['raw_frames'] == 51712
               and run['raw_hash'] == '79065b78b8a97fa8056b4899c4c5a3ce62bd28f0b766c5e93b0a9f4ce2fcfada',
               'Reached decode receipt changed')
        modules = set()
        for line in log.splitlines():
            if line.startswith('module '):
                _, name, path = line.split(' ', 2)
                q.need(Path(path).resolve() == (q.INSTALL/'bin'/name).resolve(), 'Unowned reached decoder')
                modules.add(name)
        q.need(modules == {'avcodec-simpsonsxma-62.dll', 'avutil-simpsonsxma-60.dll', 'libwinpthread-1.dll'},
               'Incomplete reached decoder module evidence')
        q.need(raw is None or raw == pcm, 'Reached decode schedules differ')
        raw = pcm
    q.need([(r['mode'], r['split']) for r in receipt['runs']] == [('xma1',0),('xma2',0),('xma2',1)],
           'Reached variant/schedule coverage changed')
    profile.update(raw_frames=len(raw)//4, raw_hash=q.sha(raw), surplus=len(raw)//4-51584,
                   runs=receipt['runs'], reused_receipt=str(folder/'receipt.json'))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--harness-dir', type=Path, default=ROOT/'build/characters-resident-xma')
    args = parser.parse_args()
    OUT.mkdir(parents=True, exist_ok=True)
    q.OUT = loc.OUT = OUT
    env = os.environ.copy(); env['PATH'] = str(q.INSTALL/'bin')+os.pathsep+env['PATH']
    q.run([sys.executable, '-B', ROOT/'tools/build_native_audio_codec.py', '--verify'], env, 'codec-verify')
    harnesses = {}
    for rate in (24000, 48000):
        source = args.harness_dir/f'harness-{rate}.cpp'
        expected = q.CPP.replace('{channels,48000,', f'{{channels,{rate},').replace('frames<=262144','frames<=524288')
        q.need(source.read_text(encoding="utf-8") == expected, 'Existing harness source differs from qualified workflow')
        exe = args.harness_dir/f'harness-{rate}.exe'
        shutil.copyfile(exe, OUT/exe.name)
        harnesses[rate] = dict(source_sha256=q.sha(source.read_bytes()), executable_sha256=q.sha(exe.read_bytes()))
    lines = ['// Generated by tools/qualify_homer_resident_xma.py after exact original bank/native decode verification.',
             '#pragma once', '#include "resident_xma.h"', 'namespace Simpsons::Audio {']
    cache = {}; reports = []
    for bank in BANKS:
        data, provenance = extract(bank)
        (OUT/bank['name']).write_bytes(data)
        profiles = loc.discover(data, audio_offset=bank['audio'], expected_count=bank['count'], expected_loops=0)
        admitted = []; excluded = {}
        for profile in profiles:
            try:
                for block in profile['blocks']:
                    key = (block['block_hash'], block['channels'], block['codec_rate'], block['frames'])
                    if key in cache:
                        block.update(copy.deepcopy(cache[key]))
                    else:
                        if block['block_hash'] == REACHED_HASH and (ROOT/'build/homer-block-qualification/receipt.json').exists():
                            q.need(q.sha(data[block['block_offset']+12:block['block_offset']+block['block_bytes']]) ==
                                   json.loads((ROOT/'build/homer-block-qualification/receipt.json').read_text(encoding="utf-8"))['packets_sha256'],
                                   'Reached receipt packet source differs')
                            reuse_reached(block)
                        else:
                            loc.qualify(data, block, env)
                        cache[key] = {k:copy.deepcopy(v) for k,v in block.items() if k not in
                            ('offset','block_offset','header','block_bytes','frames','channels','playback_rate',
                             'selector','codec_rate','restored_ff','block_hash')}
                admitted.append(profile)
            except RuntimeError as error:
                excluded[str(profile['offset'])] = str(error)
                print('UNSUPPORTED', bank['name'], profile['offset'], str(error).splitlines()[0], flush=True)
        q.need(any(p['offset'] == bank['reached'] for p in admitted), 'Reached Homer record did not qualify')
        normals = [p['blocks'][0] for p in admitted]
        symbol = bank['symbol']
        lines += ['// '+bank['name']+' SHA256 '+bank['sha'],
                  f'inline constexpr std::array<ResidentXmaProfile,{len(normals)}> {symbol}ResidentXmaProfiles = {{{{']
        lines += ['    '+loc.row(p)+',' for p in normals]+['}};',
                  f'inline constexpr std::array<ResidentLoopProfile,0> {symbol}ResidentLoopProfiles = {{}};']
        reports.append(dict(bank=bank, provenance=provenance, profiles=admitted, excluded=excluded,
                            scanned_candidates=len(profiles), raw_eof_sent=False))
        print('PASS', bank['name'], len(normals), 'records; 0 loops;', len(excluded), 'excluded', flush=True)
    lines += ['}']
    (OUT/'report.json').write_text(json.dumps(dict(harnesses=harnesses, banks=reports),indent=2)+'\n', encoding="utf-8")
    (ROOT/'audio/homer_resident_xma_certificates.h').write_text('\n'.join(lines)+'\n', encoding="utf-8")


if __name__ == '__main__':
    main()
