"""Qualify all supported records of the exact original loc_global.sbk."""
import argparse
import copy
import json
import os
from pathlib import Path
import shutil
import struct
import sys
sys.dont_write_bytecode = True
import qualify_loc_resident_xma as loc
import qualify_resident_xma as q
from extract_resource import select_payload

ROOT = q.ROOT
OUT = ROOT/'build/loc-global-resident-xma'
BANK_HASH = '145197be5688def500325f86d2c4896ac3ddbf751be95c388393e22bbec2e6df'
STR_HASH = '66d4d27bb4381135a543ed85bb6aa9d6bfe550eca46f9d9d43fcc1aa11e022f0'
REACHED_HASH = '02afc69859b1855cfd62ff1750d94158f4d658775de0dc2e2a98c2bf95c41b0a'


def extract():
    root = ROOT/'Simpsons Game, The (USA)'
    data, provenance = select_payload(root/'loc/loc_global.str', 2, 'loc_global.sbk', root)
    q.need(len(data) == 2948197 and q.sha(data) == BANK_HASH
           and provenance['source']['sha256'] == STR_HASH, 'Original loc_global identity changed')
    q.need(struct.unpack_from('>IIII', data, 8) == (0x17C30,0x2B7FE5,0x17C80,0x2B7FE5),
           'Original loc_global split changed')
    return data, provenance


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--harness-dir', type=Path, default=ROOT/'build/characters-resident-xma')
    args = parser.parse_args()
    data, provenance = extract()
    profiles = loc.discover(data, audio_offset=0x17C80, expected_count=479, expected_loops=0)
    reached = next(p['blocks'][0] for p in profiles if p['offset'] == 0x1CDA89)
    q.need(reached['block_hash'] == REACHED_HASH and reached['header'] == '0300bb8000001648'
           and reached['block_bytes'] == 1561 and reached['frames'] == 5704
           and reached['restored_ff'] == 499, 'Reached loc_global record changed')
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT/'loc_global.sbk').write_bytes(data)
    q.OUT = loc.OUT = OUT
    env = os.environ.copy(); env['PATH'] = str(q.INSTALL/'bin')+os.pathsep+env['PATH']
    q.run([sys.executable, '-B', ROOT/'tools/build_native_audio_codec.py', '--verify'], env, 'codec-verify')
    harnesses = {}
    for rate in (24000,48000):
        source = args.harness_dir/f'harness-{rate}.cpp'
        expected = q.CPP.replace('{channels,48000,', f'{{channels,{rate},').replace('frames<=262144','frames<=524288')
        q.need(source.read_text(encoding="utf-8") == expected, 'Existing qualification harness source changed')
        exe = args.harness_dir/f'harness-{rate}.exe'
        shutil.copyfile(exe, OUT/exe.name)
        harnesses[rate] = dict(source_sha256=q.sha(source.read_bytes()), executable_sha256=q.sha(exe.read_bytes()))
    admitted = []; excluded = {}; cache = {}
    # Qualify the reached source first, but retain original offset ordering in certificates.
    for profile in sorted(profiles, key=lambda p:(p['offset'] != 0x1CDA89,p['offset'])):
        try:
            for block in profile['blocks']:
                key = (block['block_hash'],block['channels'],block['codec_rate'],block['frames'])
                if key in cache:
                    block.update(copy.deepcopy(cache[key]))
                else:
                    loc.qualify(data, block, env)
                    cache[key] = {k:copy.deepcopy(v) for k,v in block.items() if k not in
                        ('offset','block_offset','header','block_bytes','frames','channels','playback_rate',
                         'selector','codec_rate','restored_ff','block_hash')}
            admitted.append(profile)
            if profile['offset'] == 0x1CDA89:
                (OUT/'reached-receipt.json').write_text(json.dumps(profile,indent=2)+'\n', encoding="utf-8")
                print('Reached PASS', json.dumps(profile['blocks'][0]), flush=True)
        except RuntimeError as error:
            excluded[str(profile['offset'])] = str(error)
            print('UNSUPPORTED', profile['offset'], str(error).splitlines()[0], flush=True)
    admitted.sort(key=lambda p:p['offset'])
    (OUT/'report.json').write_text(json.dumps(dict(bank_sha256=BANK_HASH, provenance=provenance,
        harnesses=harnesses, scanned_candidates=len(profiles), profiles=admitted, excluded=excluded,
        raw_eof_sent=False),indent=2)+'\n')
    q.need(any(p['offset'] == 0x1CDA89 for p in admitted), 'Reached loc_global record failed qualification')
    lines = ['// Generated by tools/qualify_loc_global_resident_xma.py after exact bank/native decode verification.',
             '// Original loc_global.sbk SHA256 '+BANK_HASH, '#pragma once', '#include "resident_xma.h"',
             'namespace Simpsons::Audio {',
             f'inline constexpr std::array<ResidentXmaProfile,{len(admitted)}> locGlobalResidentXmaProfiles = {{{{']
    lines += ['    '+loc.row(p['blocks'][0])+',' for p in admitted]
    lines += ['}};', 'inline constexpr std::array<ResidentLoopProfile,0> locGlobalResidentLoopProfiles = {};', '}']
    (ROOT/'audio/loc_global_resident_xma_certificates.h').write_text('\n'.join(lines)+'\n', encoding="utf-8")
    print('PASS loc_global.sbk',len(admitted),'records; 0 loops;',len(excluded),'excluded',flush=True)


if __name__ == '__main__':
    main()
